name: SSH Connection

on:
  schedule:
    - cron: '0 7 * * *' # 7h sáng UTC mỗi ngày
  workflow_dispatch:

jobs:
  ssh-connection:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Connect to SSH
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" \
        ssh -o StrictHostKeyChecking=no \
        -L 5900:localhost:5900 \
        root@adm.segfault.net "export SECRET=${{ secrets.SECRET }} && echo \$SECRET && sleep 30"
