name: SSH Connection

on:
  schedule:
    - cron: '0 0 7 * * *' # Lệnh này sẽ chạy vào 7h sáng UTC mỗi ngày.
  workflow_dispatch: # Cho phép bạn chạy thủ công từ GitHub Actions.

jobs:
  ssh-connection:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: Connect to SSH
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o "StrictHostKeyChecking=no" -L5900:0:5900 -o "SetEnv SECRET=${{ secrets.SECRET }}" root@adm.segfault.net
