name: Tmate Debug 4h

on:
  workflow_dispatch: 

jobs:
  debug:
    runs-on: ubuntu-latest
    timeout-minutes: 240 # Giới hạn 4 giờ

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: false
