name: SSH Connection

on:
  schedule:
    - cron: '0 7 * * *' # chạy 7h sáng UTC (14h VN) mỗi ngày
  workflow_dispatch: # vẫn cho chạy tay nếu cần

jobs:
  ssh-connection:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Connect to SSH
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" \
        ssh -o StrictHostKeyChecking=no \
        -L 5900:localhost:5900 \
        root@adm.segfault.net "
          export SECRET='${{ secrets.SECRET }}'
          echo 'Connected via SSH ✅'
          echo 'SECRET='$SECRET
          # Lệnh cần chạy trên server để duy trì hoặc thực thi
          uptime
        "
